default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: purple_door_development

test:
  <<: *default
  database: purple_door_test

production:
  <<: *default
  database: purple_door_production
